# Generated by Django 5.0 on 2023-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_room_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="defaultPermission",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
