# Generated by Django 4.2.7 on 2023-12-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_ipadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_session',
            name='user',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='user_session',
        ),
    ]
